### ISSUE TITLE
search/tweetsのサンプル

### ISSUE THREAD

**Issue by sbmegaman** [mpyw/HardBotter#2]
search/tweets APIのサンプルもあるとありがたいです。
自分で特定ワードに反応するコードを書いてみましたが、markがうまく働きませんでした。

**Comment by mpyw** [comment]
返信が一年越しになってしまい，もはや需要が有るかどうかすらわかりませんが，一応返信させていただきます…申し訳ないです．

最近気が向いたので，リファクタリングとテストを行ってみました．検索APIに関してmarkが動作するシナリオでテストを書いてみましたが，（あくまでテストの上では）問題なく動作します．この部分はTwistOAuthの頃から大きく手を加えてはいません．

``` php
foreach ($bot->get('search/tweets', ['q' => 'php'])->statuses as $status) {
    if (...) {
        $bot->mark($status);
    }
}
```

のような感じで動作すると思います．
